---

- name: Install docker packages
  package:
    name:
      - docker
      - docker-compose

- name: Install docker configuration template
  template:
    src: docker-daemon.json.j2
    dest: /etc/docker/daemon.json

- name: Start and enable docker deamon
  service:
    name: docker
    state: started
    enabled: yes
